backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'blog'
    label: 'Публикации'
    folder: 'content/russian/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - label: 'Название'
        name: 'title'
        widget: 'string'
      - label: 'Дата'
        name: 'date'
        widget: 'datetime'
      - label: 'Автор'
        name: 'author'
        widget: 'relation'
        collection: "author"
        searchFields: ["title"]
        valueField: "id"
      - label: 'Обложка'
        name: 'image'
        widget: 'image'
        hint: 'Не используйте разрешение больше 1500'
      - label: 'Обои'
        name: 'bg_image'
        widget: 'string'
        hint: 'На них отобразится название белыми буквами. Используйте тёмное изображение. Добавьте ссылку на изображение, воспользуйтесь https://imgbb.com/'
        required: false
      - label: 'Категория'
        name: 'categories'
        widget: 'list'
      - label: 'Теги'
        name: 'tags'
        widget: 'list'
      - label: 'Пост'
        name: 'body'
        widget: 'markdown'
  - name: 'author'
    label: 'Авторы'
    folder: 'content/russian/author'
    create: true
    slug: '{{id}}'
    editor:
      preview: true
    fields:
      - label: 'Имя'
        name: 'title'
        widget: 'string'
      - label: 'Идентификатор'
        name: 'id'
        widget: 'string'
        pattern: ['^[a-zA-Z0-9]*$', 'Только латинские буквы и арабские цифры!']
      - label: 'Фото'
        name: 'photo'
        widget: 'string'
        hint: 'Используйте сервис https://imgbb.com/ Добавьте ссылку на миниатюру (thumbnail)'
        required: false
      - label: 'Обои'
        name: 'bg_image'
        widget: 'string'
        hint: 'На них отобразится имя белыми буквами. Используйте тёмное изображение'
        required: false
      - label: 'Об авторе'
        name: 'body'
        widget: 'text'
        required: false