backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow
media_folder: 'static/img/blog'
public_folder: '/img/blog'
collections:
  - name: 'blog'
    label: 'Публикации'
    folder: 'content/russian/blog'
    create: true
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
    editor:
      preview: true
    fields:
      - label: 'Название'
        name: 'title'
        widget: 'string'
      - label: 'Дата'
        name: 'date'
        widget: 'datetime'
      - label: 'Автор'
        name: 'author'
        widget: 'relation'
        collection: "author"
        searchFields: ["title"]
        valueField: "id"
        displayFields: ["title", "id"]
      - label: 'Обложка'
        name: 'image'
        widget: 'image'
        allow_multiple: false
        hint: 'Сожмите в MozJPEG, используя https://squoosh.app/'
        media_folder: 'assets/covers'
        # public_folder: '/covers'
      - label: 'Категория'
        name: 'categories'
        widget: 'list'
      - label: 'Теги'
        name: 'tags'
        widget: 'list'
      - label: 'Пост'
        name: 'body'
        widget: 'markdown'
  - name: 'author'
    label: 'Авторы'
    folder: 'content/russian/author'
    create: true
    slug: '{{id}}'
    editor:
      preview: true
    fields:
      - label: 'Имя'
        name: 'title'
        widget: 'string'
      - label: 'Идентификатор'
        name: 'id'
        widget: 'string'
        pattern: ['^[a-zA-Z0-9]*$', 'Не подходит']
        hint: 'Только латинские буквы и арабские цифры'
      - label: 'Фото'
        name: 'photo'
        widget: 'string'
        pattern: ['https:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}', 'Ниже подсказка']
        hint: 'Вставьте URL изображения. Размер 200х200px. Обязательно https://. Воспользуйтесь сервисом https://www.techpowerup.org/upload'
        required: false
      - label: 'Об авторе'
        name: 'body'
        widget: 'text'
        required: false